/**
 * Ethernet -- the link layer, and the one layer that is rewritten at every single hop.
 *
 * This file exists to make one fact demonstrable: **a frame is addressed to the next
 * machine on the wire, not to the destination**. The IP header carries the endpoints
 * and survives the whole journey untouched; the Ethernet header carries this hop and
 * this hop only, and is thrown away and rebuilt by every router along the path. Most
 * diagrams draw a packet as one object sliding along a line, which quietly teaches the
 * opposite.
 *
 * So the API is deliberately split in two:
 *
 * - {@link encapsulateEthernet} / {@link decapsulateEthernet} -- what a host does: put
 *   a frame *around* a packet before it goes on the wire, strip it off on arrival.
 * - {@link rewriteEthernetHeader} -- what a router does: same packet, same id, brand
 *   new source and destination MAC.
 *
 * ## What is counted in `sizeBytes`
 *
 * The 14-byte header only. The 4-byte frame check sequence and the preamble are
 * generated by the NIC and are not part of what a capture shows, so counting them would
 * make every number here disagree with Wireshark. {@link ethernetPadding} and
 * {@link frameOnWireBytes} expose the rest for when the UI wants to explain it.
 */

import { formatMac, mac } from '@/core/net/address';
import { toHex } from '@/core/net/bytes';
import type { PDU, ProtocolLayer } from '@/core/types/pdu';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Destination MAC (6) + source MAC (6) + EtherType (2). */
export const ETHERNET_HEADER_BYTES = 14;

/** The trailing CRC. Real, but never shown in a capture -- see the file note. */
export const ETHERNET_FCS_BYTES = 4;

/**
 * The largest payload a standard Ethernet frame carries: 1500 bytes.
 *
 * This single number is why IPv4 fragmentation exists at all, and why the default TCP
 * MSS is 1460 -- 1500 less a 20-byte IP header and a 20-byte TCP header.
 */
export const ETHERNET_MTU = 1500;

/**
 * The smallest payload a frame may carry: 46 bytes. Shorter ones are padded up to it.
 *
 * A holdover from the original shared coaxial segment: a frame had to stay on the wire
 * long enough that a collision at the far end would reach the sender before it stopped
 * transmitting. Nothing collides on a modern switched link, but the minimum stayed.
 */
export const ETHERNET_MIN_PAYLOAD = 46;

/** The EtherTypes this simulation emits, keyed by the name a capture would show. */
export const ETHER_TYPES = {
  ipv4: 0x0800,
  arp: 0x0806,
  ipv6: 0x86dd,
} as const;

/** Key of {@link ETHER_TYPES} -- which protocol the frame is carrying. */
export type EtherTypeName = keyof typeof ETHER_TYPES;

const ETHER_TYPE_LABELS: Record<EtherTypeName, string> = {
  ipv4: 'IPv4',
  arp: 'ARP',
  ipv6: 'IPv6',
};

// ---------------------------------------------------------------------------
// Framing
// ---------------------------------------------------------------------------

/**
 * The three fields of an Ethernet II header: who this hop is between, and what is
 * inside.
 *
 * Held as a struct rather than as rendered {@link ProtocolLayer} fields because the
 * simulation *transforms* it -- a router swaps both addresses -- and only renders it at
 * the end. Deriving the display from the state, never the other way round, is what
 * stops the hop table and the packet inspector from ever disagreeing.
 */
export interface EthernetFraming {
  /** MAC of the interface putting the frame on this wire, in canonical colon form. */
  readonly sourceMac: string;
  /** MAC of the next machine on this wire -- never the far end of the journey. */
  readonly destinationMac: string;
  /** Which protocol the payload is, so the receiver knows who to hand it to. */
  readonly etherType: EtherTypeName;
}

/**
 * Build framing for one hop, validating both addresses.
 *
 * Addresses go through `parseMac`, so a typo in a scenario file throws at import time
 * rather than rendering as a plausible-looking wrong address in the hop table.
 */
export function ethernetFraming(
  sourceMac: string,
  destinationMac: string,
  etherType: EtherTypeName = 'ipv4',
): EthernetFraming {
  return {
    sourceMac: formatMac(mac(sourceMac)),
    destinationMac: formatMac(mac(destinationMac)),
    etherType,
  };
}

/**
 * The framing for the next hop: same payload, both addresses replaced.
 *
 * This is the whole of what a router does at layer 2. The EtherType carries over
 * because the thing inside did not change -- only the two machines either side of it.
 */
export function rewriteFraming(
  framing: EthernetFraming,
  next: { sourceMac: string; destinationMac: string },
): EthernetFraming {
  return ethernetFraming(next.sourceMac, next.destinationMac, framing.etherType);
}

/** Padding bytes a frame carrying `payloadBytes` needs to reach the 46-byte floor. */
export function ethernetPadding(payloadBytes: number): number {
  return Math.max(0, ETHERNET_MIN_PAYLOAD - payloadBytes);
}

/**
 * What the NIC actually clocks onto the wire: header, payload, padding, and FCS.
 *
 * Deliberately larger than `PDU.sizeBytes`; use it for the "why is a 20-byte packet
 * still 64 bytes on the wire?" explanation, not for the hop table.
 */
export function frameOnWireBytes(payloadBytes: number): number {
  return (
    ETHERNET_HEADER_BYTES +
    payloadBytes +
    ethernetPadding(payloadBytes) +
    ETHERNET_FCS_BYTES
  );
}

/** True if `payloadBytes` will not fit in one frame on a link with this MTU. */
export function exceedsMtu(payloadBytes: number, mtu: number = ETHERNET_MTU): boolean {
  return payloadBytes > mtu;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/** The Ethernet II header as the inspector shows it, in wire order. */
export function buildEthernetLayer(framing: EthernetFraming): ProtocolLayer {
  const etherType = ETHER_TYPES[framing.etherType];
  return {
    layer: 'link',
    protocol: 'Ethernet II',
    fields: [
      {
        name: 'Destination MAC',
        value: framing.destinationMac,
        bits: 48,
        note: 'The next machine on this wire -- not the far end of the journey. Rewritten at every hop.',
      },
      {
        name: 'Source MAC',
        value: framing.sourceMac,
        bits: 48,
        note: 'The interface that put this frame on the wire. Also rewritten at every hop.',
      },
      {
        name: 'EtherType',
        value: `${toHex(etherType, { bits: 16 })} (${ETHER_TYPE_LABELS[framing.etherType]})`,
        bits: 16,
        note: 'Which protocol is inside, so the receiver knows which stack to hand the payload to.',
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// Encapsulation
// ---------------------------------------------------------------------------

/**
 * Wrap a packet in a frame: push the link header onto the front of the stack and add
 * its 14 bytes to the total.
 *
 * `PDU.layers` is ordered outermost first, so encapsulating is an unshift -- the header
 * a receiving NIC reads first ends up at index 0.
 */
export function encapsulateEthernet(pdu: PDU, framing: EthernetFraming): PDU {
  return {
    ...pdu,
    layers: [buildEthernetLayer(framing), ...pdu.layers],
    sizeBytes: pdu.sizeBytes + ETHERNET_HEADER_BYTES,
  };
}

/**
 * Strip the frame off, exposing the packet inside.
 *
 * Returns the PDU unchanged when the outermost layer is not Ethernet, so a caller can
 * decapsulate defensively without checking first.
 */
export function decapsulateEthernet(pdu: PDU): PDU {
  if (linkLayerIndex(pdu) !== 0) {
    return pdu;
  }
  return {
    ...pdu,
    layers: pdu.layers.slice(1),
    sizeBytes: pdu.sizeBytes - ETHERNET_HEADER_BYTES,
  };
}

/**
 * The per-hop MAC rewrite: replace the link header in place, leaving everything inside
 * it -- and the PDU's id, size, and summary -- exactly as they were.
 *
 * The unchanged id is the point. It is the same packet; a router did not create a new
 * one, it re-addressed the envelope. Following one id across every hop of the timeline
 * is how the UI proves that.
 */
export function rewriteEthernetHeader(pdu: PDU, framing: EthernetFraming): PDU {
  const index = linkLayerIndex(pdu);
  if (index < 0) {
    return encapsulateEthernet(pdu, framing);
  }
  const layers = [...pdu.layers];
  layers[index] = buildEthernetLayer(framing);
  return { ...pdu, layers };
}

function linkLayerIndex(pdu: PDU): number {
  return pdu.layers.findIndex(
    (layer) => layer.layer === 'link' && layer.protocol.startsWith('Ethernet'),
  );
}
