/**
 * Simulated `ping`: eight bytes of header, and one very badly understood result.
 *
 * The mechanism is almost nothing. A host puts an ICMP Echo Request on the wire, another
 * host is required by RFC 792 to send the payload straight back as an Echo Reply, and the
 * sender subtracts the two timestamps. There is no connection, no port, no application
 * involved at either end -- the reply is generated by the kernel's IP stack, which is
 * precisely why a reply proves so much less than it looks like it proves.
 *
 * ## What this file is really for
 *
 * Every path in `paths.ts` produces a number, and only one of them produces a number that
 * means what a beginner reads into it. The rest exist so that {@link explainOutcome} has
 * something to explain:
 *
 * - **100% loss does not mean the host is down.** ICMP is a separate protocol from the one
 *   carrying the traffic anybody cares about, and filtering it is a default on a large
 *   fraction of the Internet. `filtered-host` serves HTTPS throughout a ping that reports
 *   total loss, and the run carries a {@link ReachabilityContrast} that says so on the
 *   same screen.
 * - **Partial loss usually is not the destination.** On `flaky-wifi` every lost probe dies
 *   at hop 1, three metres from the laptop.
 * - **A reply is not a health check.** `rate-limited` answers two probes in three while
 *   perfectly healthy, and a kernel that answers echoes says nothing about whether the
 *   application above it is running.
 * - **Down looks different from filtered**, if you read *who* answered: `dead-host` gets
 *   an ICMP Destination Unreachable from the *router*, not silence from the host.
 *
 * ## Determinism
 *
 * Jitter, loss, and the rate limiter all draw from `@/core/sim/rng`, forked per concern
 * so that adding one randomised detail cannot shift another. The same path and seed
 * produce a deep-equal `PingRun`; no clock is read anywhere in this file.
 *
 * Nothing here can reach a network. It takes a {@link DiagnosticPath} -- a bundled
 * fixture -- and never a host name from a caller.
 */

import {
  buildIpv4Layer,
  internetChecksum,
  ipv4Header,
  IPV4_HEADER_BYTES,
  IP_PROTOCOLS,
} from '@/core/protocols/ipv4/ipv4';
import { toHex } from '@/core/net/bytes';
import { createRng } from '@/core/sim/rng';
import { summarizePhases, type SimResult } from '@/core/sim/result';
import type { RfcRef, SimEvent } from '@/core/types/events';
import type { PDU, ProtocolLayer } from '@/core/types/pdu';
import type { Topology } from '@/core/types/topology';

import {
  buildTopology,
  conditionsOf,
  hopCount,
  linkIdAt,
  nodeChain,
  oneWayMs,
  type DiagnosticPath,
} from './path';

// ---------------------------------------------------------------------------
// ICMP, the eight bytes of it that ping uses
// ---------------------------------------------------------------------------

/** ICMP type 8: "send this back to me". */
export const ICMP_ECHO_REQUEST = 8;
/** ICMP type 0: "here it is". */
export const ICMP_ECHO_REPLY = 0;
/** ICMP type 3, the error that means the packet could not be delivered. */
export const ICMP_DESTINATION_UNREACHABLE = 3;
/** Code 1 of type 3: the last router could not reach the host on its own subnet. */
export const ICMP_CODE_HOST_UNREACHABLE = 1;
/** Code 13 of type 3: a filter refused to forward it, and admitted as much. */
export const ICMP_CODE_ADMIN_PROHIBITED = 13;

/** Type, code, checksum, identifier, sequence: four 16-bit words and nothing else. */
export const ICMP_HEADER_BYTES = 8;

/** What `ping` sends by default. 56 + 8 is the "64 bytes from ..." in every output. */
export const DEFAULT_PAYLOAD_BYTES = 56;

const RFC_792: RfcRef = { rfc: 792, title: 'Internet Control Message Protocol' };
const RFC_1122_ECHO: RfcRef = {
  rfc: 1122,
  section: '3.2.2.6',
  title: 'Requirements for Internet Hosts -- Communication Layers',
};

/** One echo message, request or reply. */
export interface IcmpEcho {
  /** {@link ICMP_ECHO_REQUEST} or {@link ICMP_ECHO_REPLY}. */
  readonly type: number;
  /** Always 0 for an echo; the field exists to subdivide the error types. */
  readonly code: number;
  /**
   * Chosen once per ping process and echoed back untouched.
   *
   * There are no ports in ICMP, so this is the whole demultiplexing story: two pings
   * running at once are told apart by the kernel on this field alone.
   */
  readonly identifier: number;
  /** Counts up per probe, and is what `icmp_seq=` prints. */
  readonly sequence: number;
  /** Bytes of data after the header. 56 by default. */
  readonly payloadBytes: number;
}

/**
 * The payload Linux `ping` sends: a run of increasing bytes from 0x10.
 *
 * Content nobody looks at, which is the point -- the receiver is required to return it
 * byte for byte, so a mismatch is a corrupted path rather than a protocol disagreement.
 * Generated rather than stored so the checksum below is computed over real bytes.
 */
export function echoPayloadPattern(bytes: number): number[] {
  return Array.from({ length: bytes }, (_, index) => (0x10 + index) & 0xff);
}

/** The message serialized, with `checksum` in the checksum field (0 while computing). */
export function icmpEchoBytes(echo: IcmpEcho, checksum = 0): number[] {
  return [
    echo.type,
    echo.code,
    (checksum >> 8) & 0xff,
    checksum & 0xff,
    (echo.identifier >> 8) & 0xff,
    echo.identifier & 0xff,
    (echo.sequence >> 8) & 0xff,
    echo.sequence & 0xff,
    ...echoPayloadPattern(echo.payloadBytes),
  ];
}

/**
 * The real one's-complement checksum over the real serialized bytes (RFC 1071).
 *
 * Unlike IPv4's, this one covers the payload as well as the header, which is why an echo
 * reply that returns the data intact also returns the same checksum -- only the type byte
 * changed, and 8 minus 0 is exactly the 0x0800 difference the two checksums show.
 */
export function icmpEchoChecksum(echo: IcmpEcho): number {
  return internetChecksum(icmpEchoBytes(echo));
}

/** Total size of the ICMP message: header plus data. */
export function icmpEchoSize(echo: IcmpEcho): number {
  return ICMP_HEADER_BYTES + echo.payloadBytes;
}

/** The echo header as the inspector shows it, in wire order, checksum computed. */
export function buildIcmpEchoLayer(echo: IcmpEcho): ProtocolLayer {
  const request = echo.type === ICMP_ECHO_REQUEST;

  return {
    layer: 'network',
    protocol: 'ICMP',
    fields: [
      {
        name: 'Type',
        value: request ? '8 (Echo Request)' : '0 (Echo Reply)',
        bits: 8,
        note: 'The only difference between the two messages. Everything else is copied back unchanged.',
      },
      {
        name: 'Code',
        value: '0',
        bits: 8,
        note: 'Subdivides a type. Echo has only one code; the error types are where this field earns its keep.',
      },
      {
        name: 'Checksum',
        value: toHex(icmpEchoChecksum(echo), { bits: 16 }),
        bits: 16,
        note: "One's-complement sum over the header and the data, unlike IPv4's, which covers only the header.",
      },
      {
        name: 'Identifier',
        value: String(echo.identifier),
        bits: 16,
        note: 'ICMP has no ports. This is how the kernel knows which of two running pings a reply belongs to.',
      },
      {
        name: 'Sequence Number',
        value: String(echo.sequence),
        bits: 16,
        note: 'Increments per probe. It is what lets the sender say which one went missing rather than only how many did.',
      },
    ],
    payloadPreview: `${echo.payloadBytes} bytes of pattern data, returned byte for byte`,
  };
}

/** An ICMP error: type 3, and the code that says why delivery failed. */
export function buildIcmpUnreachableLayer(code: number, quoted: string): ProtocolLayer {
  const label =
    code === ICMP_CODE_HOST_UNREACHABLE
      ? '1 (Host Unreachable)'
      : '13 (Communication Administratively Prohibited)';
  const note =
    code === ICMP_CODE_HOST_UNREACHABLE
      ? 'The last router can reach the subnet but got no answer to its ARP. The address is empty.'
      : 'A filter refused to forward the packet and said so. The target may be perfectly healthy behind it.';

  return {
    layer: 'network',
    protocol: 'ICMP',
    fields: [
      { name: 'Type', value: '3 (Destination Unreachable)', bits: 8 },
      { name: 'Code', value: label, bits: 8, note },
      { name: 'Unused', value: '0', bits: 32 },
    ],
    payloadPreview: `IPv4 header + first 8 bytes of the echo request to ${quoted}`,
  };
}

// ---------------------------------------------------------------------------
// One probe
// ---------------------------------------------------------------------------

/** How one probe ended. */
export type ProbeOutcome =
  /** An Echo Reply came back. */
  | 'reply'
  /** Nothing came back before the deadline -- and this is the ambiguous one. */
  | 'timeout'
  /** A router answered type 3 code 13: it will not forward this, by policy. */
  | 'prohibited'
  /** A router answered type 3 code 1: the address on its subnet is empty. */
  | 'host-unreachable';

/** One echo request and whatever happened to it. */
export interface PingProbe {
  readonly sequence: number;
  /** Virtual millisecond the request left the source. */
  readonly sentAt: number;
  /** Virtual millisecond the answer arrived, or the deadline passed. */
  readonly settledAt: number;
  readonly outcome: ProbeOutcome;
  /** Round trip in milliseconds. Absent on a timeout, because nothing was measured. */
  readonly rttMs?: number;
  /** Address that answered. Absent on a timeout -- that is the whole problem with one. */
  readonly responder?: string;
  /**
   * TTL left on the reply when it arrived.
   *
   * Present only for an Echo Reply. Subtract it from the round number the sender guesses
   * the far end started at (64, or 128 on Windows) and you have the hop count of the
   * *return* path -- which is not necessarily the one traceroute drew.
   */
  readonly replyTtl?: number;
  /** Size of the reply as ping reports it: ICMP header plus data. */
  readonly bytes: number;
  /** `SimNode.id` where the probe or its reply died. Absent when it came back. */
  readonly lostAt?: string;
  /** The line ping would print for this probe. */
  readonly line: string;
}

// ---------------------------------------------------------------------------
// Statistics
// ---------------------------------------------------------------------------

/** The summary block at the end of a ping run. */
export interface PingStats {
  readonly sent: number;
  readonly received: number;
  /** Whole-number percent, as ping prints it. */
  readonly lossPercent: number;
  /** Wall time of the whole run, in virtual milliseconds. */
  readonly elapsedMs: number;
  readonly minMs?: number;
  readonly avgMs?: number;
  readonly maxMs?: number;
  /**
   * Mean deviation, the way `iputils` computes it: the population standard deviation of
   * the round trips, not the average absolute deviation the name suggests.
   *
   * It is the jitter number. A small mean with a large mdev is a path that is fast on
   * average and unusable for anything interactive.
   */
  readonly mdevMs?: number;
}

function round3(value: number): number {
  return Math.round(value * 1000) / 1000;
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

/** Fold the probes into the block ping prints after the last one. */
export function summarize(probes: readonly PingProbe[], elapsedMs: number): PingStats {
  const times = probes
    .map((probe) => probe.rttMs)
    .filter((rtt): rtt is number => rtt !== undefined);
  const sent = probes.length;
  const received = times.length;
  const base: PingStats = {
    sent,
    received,
    lossPercent: sent === 0 ? 0 : Math.round(((sent - received) / sent) * 100),
    elapsedMs: round2(elapsedMs),
  };

  if (received === 0) return base;

  const sum = times.reduce((total, value) => total + value, 0);
  const avg = sum / received;
  const variance =
    times.reduce((total, value) => total + (value - avg) ** 2, 0) / received;

  return {
    ...base,
    minMs: round3(Math.min(...times)),
    avgMs: round3(avg),
    maxMs: round3(Math.max(...times)),
    mdevMs: round3(Math.sqrt(variance)),
  };
}

// ---------------------------------------------------------------------------
// The part that is not a number
// ---------------------------------------------------------------------------

/**
 * A TCP connection attempt to port 443, run beside the ping and reported next to it.
 *
 * This is the answer to "is the host up", and the ping is not. It is carried in the run
 * rather than left to the UI because the contrast is the lesson: a screen showing 100%
 * packet loss and a completed handshake at the same moment settles the question in a way
 * a paragraph cannot.
 *
 * In Learn mode this is simulated like everything else. Live mode's equivalent is a real
 * TCP connect, and the UI there is required to label it as connect timing rather than as
 * a ping -- they measure different things through different protocols.
 */
export interface ReachabilityContrast {
  readonly port: number;
  readonly connected: boolean;
  /** Time to complete the handshake, in milliseconds. Absent when it did not. */
  readonly connectMs?: number;
  readonly summary: string;
}

/** What the result does and does not establish. */
export interface PingVerdict {
  /** The result in one line, as an operator would say it out loud. */
  readonly headline: string;
  /** What it proves. Deliberately narrower than the headline sounds. */
  readonly proves: string;
  /** What it does not prove. */
  readonly doesNotProve: string;
  /** Everything that could produce this output, most likely first. */
  readonly causes: readonly string[];
  /** The question to ask next, since this one did not answer it. */
  readonly nextStep: string;
}

/**
 * The four reasons a missing echo reply is weak evidence, independent of any one run.
 *
 * Shown beside every result rather than only beside the filtered one, because the
 * mistake this module exists to prevent is made on the *clean* runs too: a learner who
 * concludes "it replied, so the service is fine" has made the same error in the other
 * direction.
 */
export const WHY_SILENCE_IS_NOT_DOWN: readonly {
  readonly claim: string;
  readonly detail: string;
}[] = [
  {
    claim: 'ICMP is a different protocol from the one you care about',
    detail:
      'An echo reply is generated by the IP stack in the kernel. It travels under protocol number 1, not 6, so a firewall rule, an ACL, or a cloud security group can permit every byte of your application traffic and still drop every probe. Filtering ICMP echo is a default in a large part of the Internet.',
  },
  {
    claim: 'Answering an echo is not evidence that a service is running',
    detail:
      'The reply comes from the kernel, which has no idea whether the web server above it crashed an hour ago. A host can answer ping perfectly while every port on it refuses connections.',
  },
  {
    claim: 'ICMP is the first traffic a busy router or host sheds',
    detail:
      'Generating ICMP is control-plane work on hardware built to forward packets, so it is rate-limited by design. Loss and latency spikes on probes routinely appear on a path that is carrying real traffic without a problem.',
  },
  {
    claim: 'The loss you measure may not be at the far end',
    detail:
      'Every hop in between can drop the request on the way out or the reply on the way back, and ping cannot tell you which. A single number for a path made of eight independent links is an average, not a diagnosis.',
  },
];

/** Turn one run into the verdict shown beside it. */
export function explainOutcome(
  path: DiagnosticPath,
  stats: PingStats,
  contrast: ReachabilityContrast,
): PingVerdict {
  const target = path.destination.hostname;

  switch (path.destination.icmp) {
    case 'filtered-silent':
      return {
        headline: `${stats.lossPercent}% packet loss, and ${target} is up the whole time.`,
        proves:
          'Nothing on the path returned an ICMP Echo Reply, and nothing returned an error either.',
        doesNotProve: `That ${target} is down. It completed a TCP handshake on port ${contrast.port} in ${contrast.connectMs} ms during this run.`,
        causes: [
          'A firewall in front of the host drops ICMP type 8 by policy',
          'The host itself is configured not to answer echo requests',
          'An ACL upstream filters ICMP without generating a rejection',
        ],
        nextStep: `Ask a question the host can answer: open a TCP connection to a port it serves, or fetch a URL. Silence from ICMP is a statement about the filter, not about ${target}.`,
      };

    case 'filtered-prohibited':
      return {
        headline: `Administratively prohibited -- ${target} is behind a filter that answers.`,
        proves:
          'A router on the path refused to forward the probe and identified itself doing it. The refusal is a policy decision, made at a named machine.',
        doesNotProve: `That ${target} is down, or even that it is unreachable by other means. Only that this router will not carry ICMP to it.`,
        causes: [
          'An ACL on the border router rejects rather than drops',
          'A security policy that deliberately reports its own existence',
        ],
        nextStep:
          'Note the address that sent the rejection -- that is the machine whose configuration decides the answer, and it is not the target.',
      };

    case 'host-down':
      return {
        headline: `Destination host unreachable -- there is nothing at ${path.destination.address}.`,
        proves:
          'The last router on the path is directly attached to that subnet, tried to deliver, got no answer to its ARP, and reported the failure. That is a positive statement, not an absence of one.',
        doesNotProve:
          'That the service moved, was renamed, or ever existed at this address. Only that the address is empty right now.',
        causes: [
          'The host is powered off or has been decommissioned',
          'A DNS record outlived the machine it pointed at',
          'The address was reassigned and nothing has claimed it yet',
        ],
        nextStep:
          'Read the responder address. An error from the router next to the target is the one case where "no reply" has been turned into a real answer.',
      };

    case 'rate-limited':
      return {
        headline: `${stats.lossPercent}% loss from a host that is answering fine.`,
        proves:
          'Some echoes came back, so the path works end to end and the far end is up.',
        doesNotProve:
          'That the path is dropping your traffic at that rate. The host caps how much ICMP it will generate; the loss is in its rate limiter, not on the wire.',
        causes: [
          'The destination rate-limits ICMP replies, as most busy hosts do',
          'A router on the path polices control-plane traffic',
        ],
        nextStep:
          'Measure the thing you actually care about. Loss on a TCP connection or on a real request is the number that describes your traffic; this one describes a rate limiter.',
      };

    default:
      break;
  }

  if (stats.lossPercent > 0) {
    return {
      headline: `${stats.lossPercent}% loss, and it is not the destination.`,
      proves: 'Some probes did not survive the round trip.',
      doesNotProve:
        'Where they died. A single loss figure summarises every link on the path at once.',
      causes: [
        'A lossy first hop -- Wi-Fi, a bad cable, a saturated uplink',
        'Congestion on an intermediate link',
        'A rate limiter somewhere on the path',
      ],
      nextStep:
        'Run the traceroute tool on the same path and compare per-hop behaviour. Loss that starts at hop 1 and continues is loss at hop 1.',
    };
  }

  return {
    headline: `${target} answers every probe in about ${stats.avgMs} ms.`,
    proves:
      'The path carries packets both ways and the IP stack at the far end is running.',
    doesNotProve:
      'That any service on the host is working. The reply was generated by the kernel, several layers below anything a user talks to.',
    causes: [],
    nextStep:
      'Treat this as a floor on latency and a check on routing, then test the actual service. A clean ping and a broken application are an ordinary combination.',
  };
}

// ---------------------------------------------------------------------------
// Running one
// ---------------------------------------------------------------------------

/** How to run a ping. */
export interface PingOptions {
  /** Probes to send. Defaults to 6. */
  readonly count?: number;
  /** Virtual milliseconds between probes. Defaults to 1000, like the real tool. */
  readonly intervalMs?: number;
  /** How long to wait before declaring a probe lost. Defaults to 1000. */
  readonly timeoutMs?: number;
  /** Data bytes after the ICMP header. Defaults to 56. */
  readonly payloadBytes?: number;
  /** Seed for jitter, loss, and the rate limiter. */
  readonly seed?: number | string;
}

/** One complete ping, ready to draw. */
export interface PingRun {
  readonly path: DiagnosticPath;
  /** The template message; only the sequence number differs between probes. */
  readonly echo: IcmpEcho;
  readonly probes: readonly PingProbe[];
  readonly stats: PingStats;
  readonly contrast: ReachabilityContrast;
  readonly verdict: PingVerdict;
  /** The whole output, line for line, as the terminal would show it. */
  readonly output: readonly string[];
  readonly topology: Topology;
  readonly result: SimResult;
}

/** Probability the rate-limited destination answers any one probe. */
const RATE_LIMIT_ANSWER_CHANCE = 2 / 3;

/** Milliseconds the far end spends turning a request into a reply. Kernel-fast. */
const ECHO_TURNAROUND_MS = 0.15;

/** Quiet virtual milliseconds after the last probe settles, so the timeline has an end. */
const TAIL_MS = 400;

/**
 * Send `count` echo requests along `path` and report what came back.
 *
 * Pure and total: the same path, options, and seed produce a deep-equal `PingRun`.
 */
export function runPing(path: DiagnosticPath, options: PingOptions = {}): PingRun {
  const count = options.count ?? 6;
  const intervalMs = options.intervalMs ?? 1000;
  const timeoutMs = options.timeoutMs ?? 1000;
  const payloadBytes = options.payloadBytes ?? DEFAULT_PAYLOAD_BYTES;
  const conditions = conditionsOf(path);

  const rng = createRng(options.seed ?? `diagnostics:ping:${path.id}`);
  const jitterRng = rng.fork('jitter');
  const lossRng = rng.fork('loss');
  const limitRng = rng.fork('rate-limit');

  // A ping process picks one identifier and keeps it. Derived from the seed so it is
  // stable across runs and visibly the same on every probe in the inspector.
  const echo: IcmpEcho = {
    type: ICMP_ECHO_REQUEST,
    code: 0,
    identifier: 1 + rng.fork('identifier').int(0xfffe),
    sequence: 1,
    payloadBytes,
  };

  const chain = nodeChain(path);
  const routerCount = path.hops.length;
  const finalTtl = hopCount(path);
  const oneWayToDestination = oneWayMs(path, finalTtl);

  /** Which machine answers an error for this path, and with which code. */
  const errorResponder = path.hops[routerCount - 1];

  const events: SimEvent[] = [];
  const pdus: Record<string, PDU> = {};
  const probes: PingProbe[] = [];

  const log = (at: number, level: 'info' | 'warn' | 'error', text: string): void => {
    events.push({ kind: 'log', at, level, text });
  };

  for (let index = 0; index < count; index += 1) {
    const sequence = index + 1;
    const sentAt = index * intervalMs;
    const request: IcmpEcho = { ...echo, sequence };

    const requestPdu = echoPdu(
      `echo-${sequence}`,
      request,
      path.source.address,
      path.destination.address,
      path.source.initialTtl,
    );
    pdus[requestPdu.id] = requestPdu;
    events.push({ kind: 'pdu-created', at: sentAt, pdu: requestPdu, atNode: chain[0]! });
    events.push({
      kind: 'node-state',
      at: sentAt,
      nodeId: chain[0]!,
      state: 'active',
      note: `echo request, seq ${sequence}`,
    });

    // The wire loses packets before any policy at the far end gets a say.
    const lostOnWire = lossRng.chance(conditions.lossRate);
    // Where a lost probe dies. Hop 1 is where a bad first link kills things, and every
    // path in this module that has loss has it there -- but the *reason* is the link, so
    // this is derived from the topology rather than declared per path.
    const lossTtl = 1;

    const answered = decideAnswer(path.destination.icmp, limitRng);
    const reachedTtl = lostOnWire ? lossTtl : finalTtl;

    // Fly the request out as far as it gets.
    let at = sentAt;
    for (let ttl = 1; ttl <= reachedTtl; ttl += 1) {
      at = pushHop(events, path, requestPdu.id, ttl, at, 'out');
    }

    if (lostOnWire) {
      events.push({
        kind: 'drop',
        at: round2(at),
        pduId: requestPdu.id,
        atNode: chain[lossTtl]!,
        reason: `Lost on the ${path.hops[lossTtl - 1]?.medium ?? 'link'} hop. Nothing at the far end ever saw this probe.`,
      });
      probes.push(
        timeoutProbe(sequence, sentAt, timeoutMs, request, chain[lossTtl]!, payloadBytes),
      );
      log(
        round2(sentAt + timeoutMs),
        'warn',
        `Request timeout for icmp_seq ${sequence}. The probe died at ${path.hops[lossTtl - 1]?.label ?? 'the first hop'} -- one hop from the laptop, and nowhere near ${path.destination.hostname}.`,
      );
      continue;
    }

    if (answered.kind === 'silent') {
      events.push({
        kind: 'node-state',
        at: round2(at),
        nodeId: chain[finalTtl]!,
        state: 'error',
        note: 'echo request dropped by policy',
      });
      events.push({
        kind: 'drop',
        at: round2(at),
        pduId: requestPdu.id,
        atNode: chain[finalTtl]!,
        reason:
          path.destination.icmp === 'rate-limited'
            ? 'Over the ICMP budget. The host is healthy and simply will not generate another reply this second.'
            : 'Dropped by a filter that has a rule about ICMP type 8. The host behind it is unaffected.',
      });
      probes.push(
        timeoutProbe(
          sequence,
          sentAt,
          timeoutMs,
          request,
          chain[finalTtl]!,
          payloadBytes,
        ),
      );
      log(
        round2(sentAt + timeoutMs),
        'warn',
        `Request timeout for icmp_seq ${sequence}. Nothing came back -- which is the least informative result this tool can produce.`,
      );
      continue;
    }

    if (answered.kind === 'error') {
      // The error comes from the last router, not from the destination, so the round trip
      // is shorter than a successful one -- a detail worth noticing in the output.
      const responderTtl = Math.max(1, routerCount);
      const unreachable = buildErrorPdu(
        `unreachable-${sequence}`,
        answered.code,
        errorResponder?.address ?? path.destination.address,
        path.source.address,
        path.destination.hostname,
      );
      pdus[unreachable.id] = unreachable;
      const generatedAt = round2(
        sentAt + oneWayMs(path, responderTtl) + conditions.icmpGenerationMs,
      );
      events.push({
        kind: 'pdu-created',
        at: generatedAt,
        pdu: unreachable,
        atNode: chain[responderTtl]!,
      });
      events.push({
        kind: 'node-state',
        at: generatedAt,
        nodeId: chain[responderTtl]!,
        state: 'error',
        note:
          answered.code === ICMP_CODE_HOST_UNREACHABLE
            ? 'ARP for the target went unanswered'
            : 'refused by policy',
      });

      let back = generatedAt;
      for (let ttl = responderTtl; ttl >= 1; ttl -= 1) {
        back = pushHop(events, path, unreachable.id, ttl, back, 'in');
      }
      const jitter = jitterRng.next() * conditions.jitterMs;
      const settledAt = round2(back + jitter);
      const responder = errorResponder?.address ?? path.destination.address;
      const line =
        answered.code === ICMP_CODE_HOST_UNREACHABLE
          ? `From ${responder} icmp_seq=${sequence} Destination Host Unreachable`
          : `From ${responder} icmp_seq=${sequence} Packet filtered`;

      probes.push({
        sequence,
        sentAt,
        settledAt,
        outcome:
          answered.code === ICMP_CODE_HOST_UNREACHABLE
            ? 'host-unreachable'
            : 'prohibited',
        responder,
        bytes: ICMP_HEADER_BYTES + IPV4_HEADER_BYTES + ICMP_HEADER_BYTES,
        lostAt: chain[responderTtl]!,
        line,
        // Deliberately no rttMs. An error is not a measurement of the target: the packet
        // turned round at a router, so timing it would attribute a router's distance to a
        // host that never saw it. Real ping leaves it out of the statistics too.
      });
      log(
        settledAt,
        'error',
        `${line}. Note the source: ${responder} is the router, not ${path.destination.hostname}. Something answered, and it was not the target -- which is exactly what makes this result useful.`,
      );
      continue;
    }

    // A real reply. Turn it round at the far end and fly it home.
    const replyPdu = echoPdu(
      `reply-${sequence}`,
      { ...request, type: ICMP_ECHO_REPLY },
      path.destination.address,
      path.source.address,
      path.destination.replyTtl,
    );
    pdus[replyPdu.id] = replyPdu;
    const repliedAt = round2(at + ECHO_TURNAROUND_MS);
    events.push({
      kind: 'pdu-created',
      at: repliedAt,
      pdu: replyPdu,
      atNode: chain[finalTtl]!,
    });
    events.push({
      kind: 'node-state',
      at: repliedAt,
      nodeId: chain[finalTtl]!,
      state: 'processing',
      note: 'echoing the payload back',
    });

    let back = repliedAt;
    for (let ttl = finalTtl; ttl >= 1; ttl -= 1) {
      back = pushHop(events, path, replyPdu.id, ttl, back, 'in');
    }

    // The destination's own return-path penalty, and nobody else's: a reply routes home
    // from wherever it was generated, so the skew of a router in the middle has nothing
    // to do with a packet the far end sent.
    const skew = path.destination.returnSkewMs ?? 0;
    const jitter = jitterRng.next() * conditions.jitterMs;
    const settledAt = round2(back + skew + jitter);
    const rttMs = round3(settledAt - sentAt);
    const replyTtl = path.destination.replyTtl - routerCount;

    // One transform at the end of the return journey rather than one per hop: ping is a
    // tool about time, and the TTL is here only so the arithmetic behind `ttl=` is
    // visible. The hop-by-hop decrement is traceroute's subject, and it does it properly.
    const arrived = withTtl(replyPdu, replyTtl);
    events.push({
      kind: 'pdu-transform',
      at: settledAt,
      pduId: replyPdu.id,
      before: replyPdu,
      after: arrived,
      atNode: chain[0]!,
      reason: `TTL ${path.destination.replyTtl} -> ${replyTtl}: one decrement per router on the way back.`,
    });

    const line = `${icmpEchoSize(request)} bytes from ${path.destination.address}: icmp_seq=${sequence} ttl=${replyTtl} time=${rttMs.toFixed(1)} ms`;
    probes.push({
      sequence,
      sentAt,
      settledAt,
      outcome: 'reply',
      rttMs,
      responder: path.destination.address,
      replyTtl,
      bytes: icmpEchoSize(request),
      line,
    });
    log(settledAt, 'info', line);
  }

  const lastSettled = probes.reduce(
    (latest, probe) => Math.max(latest, probe.settledAt),
    0,
  );
  const elapsedMs = round2(Math.max(lastSettled, (count - 1) * intervalMs));
  const stats = summarize(probes, elapsedMs);
  const contrast = tcpContrast(path, oneWayToDestination, jitterRng.next());
  const verdict = explainOutcome(path, stats, contrast);

  pushPhases(events, path, probes, contrast, verdict);
  pushAnnotations(events, path, probes);

  const durationMs = round2(elapsedMs + TAIL_MS);
  const sorted = [...events].sort((a, b) => a.at - b.at);

  return {
    path,
    echo,
    probes,
    stats,
    contrast,
    verdict,
    output: formatOutput(path, echo, probes, stats),
    topology: buildTopology(path),
    result: {
      events: sorted,
      phases: summarizePhases(sorted, durationMs),
      durationMs,
      pdus,
    },
  };
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

type Answer = { kind: 'reply' } | { kind: 'silent' } | { kind: 'error'; code: number };

/** What the far end does with this particular probe. */
function decideAnswer(
  policy: DiagnosticPath['destination']['icmp'],
  rng: { chance(probability: number): boolean },
): Answer {
  switch (policy) {
    case 'echo':
      return { kind: 'reply' };
    case 'rate-limited':
      return rng.chance(RATE_LIMIT_ANSWER_CHANCE)
        ? { kind: 'reply' }
        : { kind: 'silent' };
    case 'filtered-silent':
      return { kind: 'silent' };
    case 'filtered-prohibited':
      return { kind: 'error', code: ICMP_CODE_ADMIN_PROHIBITED };
    case 'host-down':
      return { kind: 'error', code: ICMP_CODE_HOST_UNREACHABLE };
  }
}

/** Fly a PDU across the link at `ttl`, outbound or inbound, and return the arrival time. */
function pushHop(
  events: SimEvent[],
  path: DiagnosticPath,
  pduId: string,
  ttl: number,
  at: number,
  direction: 'out' | 'in',
): number {
  const chain = nodeChain(path);
  const nearer = chain[ttl - 1]!;
  const further = chain[ttl]!;
  const from = direction === 'out' ? nearer : further;
  const to = direction === 'out' ? further : nearer;
  const hop = path.hops[ttl - 1];
  const durationMs = round2(hop ? hop.linkMs : path.destination.linkMs);

  events.push({
    kind: 'transmit',
    at: round2(at),
    pduId,
    from,
    to,
    durationMs,
    linkId: linkIdAt(path, ttl),
  });

  return round2(at + durationMs);
}

/** The probe record for something that never came back. */
function timeoutProbe(
  sequence: number,
  sentAt: number,
  timeoutMs: number,
  request: IcmpEcho,
  lostAt: string,
  payloadBytes: number,
): PingProbe {
  return {
    sequence,
    sentAt,
    settledAt: round2(sentAt + timeoutMs),
    outcome: 'timeout',
    bytes: ICMP_HEADER_BYTES + payloadBytes,
    lostAt,
    line: `Request timeout for icmp_seq ${request.sequence}`,
  };
}

/** An echo request or reply, wrapped in the IPv4 header that carries it. */
function echoPdu(
  id: string,
  echo: IcmpEcho,
  sourceIp: string,
  destinationIp: string,
  ttl: number,
): PDU {
  const request = echo.type === ICMP_ECHO_REQUEST;
  return {
    id,
    layers: [
      ipv4LayerFor(sourceIp, destinationIp, ttl, icmpEchoSize(echo)),
      buildIcmpEchoLayer(echo),
    ],
    sizeBytes: IPV4_HEADER_BYTES + icmpEchoSize(echo),
    summary: `ICMP Echo ${request ? 'Request' : 'Reply'} seq ${echo.sequence} ${sourceIp} -> ${destinationIp}`,
  };
}

/** An ICMP error travelling home from a router. */
function buildErrorPdu(
  id: string,
  code: number,
  sourceIp: string,
  destinationIp: string,
  quoted: string,
): PDU {
  // Type 3 quotes the failed datagram's header plus eight bytes, which is how the sender
  // matches the error to the probe that caused it.
  const payload = IPV4_HEADER_BYTES + ICMP_HEADER_BYTES;
  return {
    id,
    layers: [
      ipv4LayerFor(sourceIp, destinationIp, 64, ICMP_HEADER_BYTES + payload),
      buildIcmpUnreachableLayer(code, quoted),
    ],
    sizeBytes: IPV4_HEADER_BYTES + ICMP_HEADER_BYTES + payload,
    summary: `ICMP Destination Unreachable (code ${code}) ${sourceIp} -> ${destinationIp}`,
  };
}

/**
 * The IPv4 header the ICMP message travels in.
 *
 * Built through `@/core/protocols/ipv4`, so the `Total Length`, the flags, and the header
 * checksum on screen are the real arithmetic over the real serialized bytes -- and the
 * TTL field carries the note that connects this tool to the next one.
 */
function ipv4LayerFor(
  sourceIp: string,
  destinationIp: string,
  ttl: number,
  payloadBytes: number,
): ProtocolLayer {
  return buildIpv4Layer(
    ipv4Header({
      sourceIp,
      destinationIp,
      ttl,
      protocol: IP_PROTOCOLS.icmp,
      payloadBytes,
    }),
  );
}

/** Replace the TTL on a PDU's IPv4 layer, keeping every other field and the id. */
function withTtl(pdu: PDU, ttl: number): PDU {
  const [network, ...rest] = pdu.layers;
  if (!network) return pdu;
  const source = network.fields.find((field) => field.name === 'Source')?.value ?? '';
  const destination =
    network.fields.find((field) => field.name === 'Destination')?.value ?? '';
  const payloadBytes = pdu.sizeBytes - IPV4_HEADER_BYTES;
  return {
    ...pdu,
    layers: [ipv4LayerFor(source, destination, ttl, payloadBytes), ...rest],
  };
}

/** The TCP check shown beside the ping. Simulated, like everything else in Learn mode. */
function tcpContrast(
  path: DiagnosticPath,
  oneWay: number,
  jitter: number,
): ReachabilityContrast {
  const port = 443;
  if (!path.destination.tcpOpen) {
    return {
      port,
      connected: false,
      summary: `No TCP connection to port ${port} either. Two independent checks agreeing is worth far more than one of them on its own.`,
    };
  }
  // A handshake is one and a half round trips, but the connection is usable after the
  // client's ACK, so what a connect timer reports is one round trip.
  const connectMs = round2(oneWay * 2 + jitter);
  return {
    port,
    connected: true,
    connectMs,
    summary: `TCP handshake to port ${port} completed in ${connectMs} ms. ${path.destination.hostname} is up and serving, whatever the ICMP column says.`,
  };
}

/** One phase per probe, plus the summary the stepper ends on. */
function pushPhases(
  events: SimEvent[],
  path: DiagnosticPath,
  probes: readonly PingProbe[],
  contrast: ReachabilityContrast,
  verdict: PingVerdict,
): void {
  for (const probe of probes) {
    events.push({
      kind: 'phase',
      at: probe.sentAt,
      id: `probe-${probe.sequence}`,
      title: `Probe ${probe.sequence}`,
      description: describeProbe(path, probe),
    });
  }

  const last = probes[probes.length - 1];
  events.push({
    kind: 'phase',
    at: last ? last.settledAt : 0,
    id: 'summary',
    title: 'What it means',
    description: `${verdict.headline} ${verdict.doesNotProve} ${contrast.summary}`,
  });
}

function describeProbe(path: DiagnosticPath, probe: PingProbe): string {
  switch (probe.outcome) {
    case 'reply':
      return `An echo request goes out with TTL ${path.source.initialTtl} and comes back ${probe.rttMs} ms later with ${probe.replyTtl} left, one decrement per router on the return path.`;
    case 'timeout': {
      const where =
        path.hops.find((hop) => hop.id === probe.lostAt)?.label ?? path.destination.label;
      return `Nothing comes back. The request died at ${where}, and from the sender's side that is indistinguishable from a host that does not exist.`;
    }
    case 'prohibited':
      return `A router answers on the target's behalf: type 3, code 13. The packet was refused by policy at ${probe.responder}, which is a fact about the filter and not about ${path.destination.hostname}.`;
    case 'host-unreachable':
      return `${probe.responder} reports type 3, code 1. It is attached to the target's subnet, tried to deliver, and found nothing there.`;
  }
}

/** Teaching notes pinned to the machine each one is about. */
function pushAnnotations(
  events: SimEvent[],
  path: DiagnosticPath,
  probes: readonly PingProbe[],
): void {
  const first = probes[0];
  if (!first) return;

  events.push({
    kind: 'annotate',
    at: first.sentAt,
    targetId: path.source.id,
    text: `Ping is eight bytes of ICMP header and some pattern data. There is no port and no connection: the identifier field is the only thing distinguishing this ping from another one running beside it, and the receiving kernel is required to send the payload straight back.`,
    reference: RFC_792,
  });

  events.push({
    kind: 'annotate',
    at: first.settledAt,
    targetId: path.destination.id,
    text:
      path.destination.icmp === 'echo'
        ? `A host is required to answer an echo request unless it has been configured not to -- and "configured not to" is common enough that no reply is weak evidence of anything. The reply is generated here, in the IP stack, with no involvement from any service running above it.`
        : `This host does not answer echo requests. That is a configuration, not a symptom: RFC 1122 requires an echo reply, but permits an administrator to disable it, and most operators of public infrastructure do.`,
    reference: RFC_1122_ECHO,
  });
}

/** The whole run as the terminal would print it. */
function formatOutput(
  path: DiagnosticPath,
  echo: IcmpEcho,
  probes: readonly PingProbe[],
  stats: PingStats,
): string[] {
  const lines = [
    `PING ${path.destination.hostname} (${path.destination.address}) ${echo.payloadBytes}(${IPV4_HEADER_BYTES + ICMP_HEADER_BYTES + echo.payloadBytes}) bytes of data.`,
    ...probes.map((probe) => probe.line),
    '',
    `--- ${path.destination.hostname} ping statistics ---`,
    `${stats.sent} packets transmitted, ${stats.received} received, ${stats.lossPercent}% packet loss, time ${Math.round(stats.elapsedMs)}ms`,
  ];

  if (stats.minMs !== undefined) {
    lines.push(
      `rtt min/avg/max/mdev = ${stats.minMs.toFixed(3)}/${stats.avgMs?.toFixed(3)}/${stats.maxMs?.toFixed(3)}/${stats.mdevMs?.toFixed(3)} ms`,
    );
  }

  return lines;
}
